import sqlite3
import sys
from pathlib import Path


DB_PATH = Path(__file__).resolve().parent / "warehouse_app.db"


def rows(sql, params=()):
    with sqlite3.connect(DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        return [dict(row) for row in conn.execute(sql, params).fetchall()]


def print_table(title, data):
    print(f"\n{title}")
    print("=" * len(title))
    if not data:
        print("No rows found.")
        return

    headers = list(data[0].keys())
    widths = {
        header: max(len(header), *(len(str(row.get(header, ""))) for row in data))
        for header in headers
    }
    line = "+-" + "-+-".join("-" * widths[header] for header in headers) + "-+"
    header_line = "| " + " | ".join(header.ljust(widths[header]) for header in headers) + " |"

    print(line)
    print(header_line)
    print(line)
    for row in data:
        print("| " + " | ".join(str(row.get(header, "")).ljust(widths[header]) for header in headers) + " |")
    print(line)


def show_triggers():
    print_table(
        "Database Row Triggers",
        rows(
            """
            SELECT name AS trigger_name,
                   tbl_name AS table_name,
                   CASE
                       WHEN sql LIKE '%AFTER INSERT%' THEN 'AFTER INSERT'
                       WHEN sql LIKE '%AFTER UPDATE%' THEN 'AFTER UPDATE'
                       ELSE 'TRIGGER'
                   END AS trigger_event
            FROM sqlite_master
            WHERE type = 'trigger'
            ORDER BY name
            """
        ),
    )


def show_alerts():
    print_table(
        "Trigger Output: Reorder Alerts",
        rows(
            """
            SELECT r.alert_id,
                   p.product_name,
                   w.warehouse_name,
                   r.current_quantity,
                   r.reorder_level,
                   r.alert_status
            FROM reorder_alerts r
            JOIN products p ON p.product_id = r.product_id
            JOIN warehouses w ON w.warehouse_id = r.warehouse_id
            ORDER BY r.alert_id DESC
            LIMIT 10
            """
        ),
    )
    print_table(
        "Trigger Output: Expiry Alerts",
        rows(
            """
            SELECT e.alert_id,
                   p.product_name,
                   w.warehouse_name,
                   e.expiry_date,
                   e.days_to_expiry,
                   e.alert_status
            FROM expiry_alerts e
            JOIN products p ON p.product_id = e.product_id
            JOIN warehouses w ON w.warehouse_id = e.warehouse_id
            ORDER BY e.alert_id DESC
            LIMIT 10
            """
        ),
    )


def run_trigger_demo():
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            """
            INSERT INTO inventory (
                product_id, warehouse_id, quantity, bin_location, bin_status, expiry_date
            )
            VALUES (1, 1, 5, 'TRIGGER-DEMO-BIN', 'OCCUPIED', date('now', '+10 day'))
            ON CONFLICT(product_id, warehouse_id, bin_location) DO UPDATE SET
                quantity = 5,
                expiry_date = date('now', '+10 day'),
                bin_status = 'OCCUPIED',
                last_stock_check = CURRENT_TIMESTAMP
            """
        )
    print("Inserted/updated one inventory row. Alerts below are generated by row triggers.")
    show_alerts()


def show_actions():
    print_table(
        "Procedure-Style Actions / Audit Log",
        rows(
            """
            SELECT log_id,
                   action_type,
                   entity_name,
                   entity_id,
                   summary,
                   created_at
            FROM action_logs
            ORDER BY log_id DESC
            LIMIT 12
            """
        ),
    )


def show_help():
    print(
        """
Usage:
  py -3.12 review_cli.py triggers
  py -3.12 review_cli.py demo-trigger
  py -3.12 review_cli.py alerts
  py -3.12 review_cli.py actions
"""
    )


def main():
    command = sys.argv[1].lower() if len(sys.argv) > 1 else "help"
    if command == "triggers":
        show_triggers()
    elif command == "demo-trigger":
        run_trigger_demo()
    elif command == "alerts":
        show_alerts()
    elif command == "actions":
        show_actions()
    else:
        show_help()


if __name__ == "__main__":
    main()
